version: '3.9'
services:
  nginx:
    image: nginx
    ports:
      - 81:80
    container_name: nginx
    volumes:
      - ./nginx-hello.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

networks:
  frontend:
    name: nginx-network
    driver: bridge
